### PR TITLE
BUG: Don't exclude `.gp` class by default

### PR DESCRIPTION
**Pull request by rkdarst**
- Immediate fix to backwards compatibility of #185.
- I'm not implying I wouldn't want to change the default later.

### CODE REVIEW

**Review by hassec — APPROVED** [review]

**Review by choldgraf — APPROVED** [review]
I'm +1 on just merging this so that we preserve old behavior. Let's do that and we can be deliberate about changing behavior back in the future.

@rkdarst are you interested in having merge rights on this repo so that you can make releases as well?

**Comment by rkdarst** [comment]
I'm quite happy without any special access here!  I would also be happy to help out, if someone ever called on me.  But I am so busy with other things, that I worry you would put effort so that I can do something, and then never have time.  Better to rely on me as a drive-by contributor until something more is needed.  let me know, you know how to find me...

**Comment by choldgraf** [comment]
From my perspective, I would like to increase the bus factor across this repository and many others in the executable books stack. We are critically under resourced for such a heavily-used stack so need all the help we can get.

**Comment by rkdarst** [comment]
yeah, I understand.  I'll try coming to the next executiblebooks meeting.  I could easily use the workflow file and do a release, but learning other release practices would take more time (docs, etc).  I'm still not sure if it's worth it for me to try to get involved short-term unless there are current emergencies.

**Comment by choldgraf** [comment]
I don't think you should feel compelled to be involved - we are all volunteers with only a couple exceptions from the initial grant. But just wanted to emphasize that from my perspective any contribution is welcome 🙂

**Comment by rkdarst** [comment]
Perhaps I was at the wrong place for the most recent executablebooks meeting.  Or perhaps it didn't happen.  Anyway, I would be happy to talk synchronously about how we can better work together on Sphinx stuff - let me know.

**Comment by rowanc1** [comment]
Yes, we did have the meeting! I didn't do a great job of advertising beforehand though. We mostly talked through MyST enhancement proposals and ways to coordinate some of our development practices.

Would be happy to have you there next time!!

**Pull request merged**
