### PR TITLE
👌 IMPROVE: Allow copying empty lines

### LINKED ISSUE #84: Copy blanklines on matches(?)
Following #83 blanklines are not captured, e.g.

```python
In [1]: import something
   ...:
   ...: print(something.__version__)
```

If the regex is set, will copy:

```python
import something
print(something.__version__)
```

### PR DESCRIPTION
**Pull request by amotl**
Dear Chris,

this is an attempt to resolve #84 reported by @chrisjsewell. Let me know what you think about it.

With kind regards,
Andreas.

---

Edit: As per discussion at https://github.com/executablebooks/sphinx-copybutton/pull/127#issuecomment-850317061 ff., this patch, now, both:
- brings in the baseline feature (f18bd05)
- _and_ makes "copying empty lines" the default behavior (da08b04).

### CODE REVIEW

**Comment by chrisjsewell** [comment]
Thanks I'll have a look soon

**Comment by amotl** [comment]
Hi @chrisjsewell and @choldgraf,

@sappelhoff suggested at https://github.com/executablebooks/sphinx-copybutton/pull/128#pullrequestreview-671037876 (thanks!):

> It's probably a better idea to stick with the #127 PR and make comments there about how it can be tweaked to make "copying empty lines" the default behavior. Otherwise, there will be two nearly identical PRs open which will confuse reviewers and will lead to diverging discussions that are easy to miss.

I will be very happy to add da08b04 to this PR instead of #128, in order to make copying empty lines the default, if both of you agree it would be the right choice.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Hi @chrisjsewell and @choldgraf,

do you also agree that we should make copying empty lines the default behavior? If you could leave a respective statement, I would add da08b04 on top of f18bd05 here in order to make that happen before a code review.

With kind regards,
Andreas.

**Comment by choldgraf** [comment]
Thanks for the ping - if there are two PRs doing very similar things it’ll be easier to just discuss in a single PR.

**Comment by amotl** [comment]
Dear Chris,

thanks for your response. I just added da08b04f to this PR.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Can you have a look at this, @choldgraf or @chrisjsewell?

**Comment by choldgraf** [comment]
hey @amotl - please be patient, we are all split across many projects and responsibilities

**Comment by amotl** [comment]
Hi Chris,

> Please be patient, we are all split across many projects and responsibilities :-)

Sure, same thing here. I didn't want to come off impatient, apologies!

With kind regards,
Andreas.

**Comment by choldgraf** [comment]
This looks great to me - the implementation seems correct, and you've added docs and test cases. I'll give this a merge and we can spot-check updates if needed. Thanks for the improvement 🎉

**Comment by amotl** [comment]
Dear @choldgraf,

thanks a stack for merging this patch!

Now, hoping without coming over too impatient again, can I humbly ask one of the maintainers to run a new release cycle? Then, we would be able to integrate it back into our documentation (https://github.com/crate/crate-docs-theme/pull/288).

With kind regards,
Andreas.

**Comment by choldgraf** [comment]
Maybe we can get #126 merged quickly and then release? If you have any comments on @sappelhof's PR perhaps that can push things forward, but I think it is quite close

**Comment by sappelhoff** [comment]
> Maybe we can get #126 merged quickly and then release?

Would anything speak against including the two translation PRs #116 #120 in that release?

**Pull request merged**
