### PR TITLE
[MAINT,ENH]: Updating copybutton CSS + docs rename

### PR DESCRIPTION
**Pull request by choldgraf**
This PR primarily updates our copybutton SVG and behavior, drawing inspiration from GitHub's copybutton. The button is now an HTML `<button>` element, and also adds a check SVG upon click

GitHub's behavior:

Behavior in this PR:

### CODE REVIEW

**Comment by choldgraf** [comment]
@sappelhoff or @amotl any thoughts on this last-minute change? I was hoping to keep it a small-enough change that we could just treat it as an improvement and not a major change, and could loop it in to the upcoming release. WDYT?

**Review by sappelhoff — DISMISSED** [review]
Looks good to me!

**Comment by choldgraf** [comment]
cool - I am gonna merge this in, and cut a release so that y'all can enjoy the new functionality :-)

**Comment by sappelhoff** [comment]
Thanks! 🩰

**Comment by amotl** [comment]
Thank you very much for the quick turnaround on this and the other recent patches!

**Pull request merged**
