### PR TITLE
✨ IMPROVE: Update copy-button.svg

### PR DESCRIPTION
**Pull request by pradyunsg**
Switch to a more minimal icon from Tabler icons!

100% up for discussion, but I reckon this will look nicer for us. It should also some #69 since the icon includes a height and width as well.

### CODE REVIEW

**Comment by choldgraf** [comment]
I think this works for me - I haven't seen that icon in docs before but if it is relatively standard then a more minimal icon sounds good (also smaller in KB too). Any particular reason you don't like the current icons?

**Comment by pradyunsg** [comment]
There's too much happening and it looks (IMO) not as nice as mkdocs-materialvs version of this. :)

**Comment by choldgraf** [comment]
Sounds good, I guess I am 50/50 on it so your vote can tip the PR in favor of merging haha.

as a general rule I think we wanna avoid rabbit holes of "differences in design opinion" because we'll spend hours going around in circles...

**Comment by pradyunsg** [comment]
Any way to make a release with this? :puppy-face:

**Pull request merged**
